name: 'My Composite Action'
description: 'A simple composite action example'
inputs:
  input1:
    description: 'First input'
    required: true
    default: 'Default value 1'
  input2:
    description: 'Second input'
    required: true
    default: 'Default value 2'
runs:
  using: 'composite'
  steps:
    - name: Step 1: Output a message
      shell: bash
      run: echo ${inputs.input1} ${inputs.input2}

    - name: Step 2: Another command
      shell: bash
      run: echo "This is the second step."