name: 'My Composite Action'
description: 'A simple composite action example'
inputs:
  input1:
    description: 'First input'
    required: true
    default: 'Default value 1'
  input2:
    description: 'Second input'
    required: true
    default: 'Default value 2'
  my-test-token:
    description: 'A test token'
    required: false
    default: ''

  
runs:
  using: 'composite'
  steps:
    - name: Output a message
      shell: bash
      run: echo ${{inputs.input1}} ${{inputs.input2}} ${{ env.ENV_PATH }} ${{ inputs.my-test-token }}

    - name: Another command
      shell: bash
      run: echo "This is the second step."