# .github/workflows/main.yml
name: Composite Action Example

on: push

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run my composite action
        uses: deepakhpe/actions-learning-pathway/.github/actions/my-composite-action@main

        with:
          input1: 'Hello'
          input2: 'World'
        secrets:
          MY_SECRET: ${{ secrets.MY_SECRET }}