# .github/workflows/main.yml
name: Composite Action Example

env:
  ENV_PATH: $GITHUB_WORKSPACE/playwright-automation
  
on: push

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run my composite action
        uses: ./.github/actions/my-composite-action

        with:
          input1: 'Hello'
          input2: 'World'
          my-test-token: ${{ secrets.MY_TEST_TOKEN }}
        # secrets:
        #   MY_TEST_TOKEN: ${{ secrets.MY_TEST_TOKEN }}